### ISSUE TITLE
HW18: Transform 기능 확장2 - Quaternion 기반의 rotation 연산 구현

### ISSUE THREAD

**Issue by sein519** [Twin-Monkeys/Poodle#31]
아래의 명세를 만족하는 Quaternion 모듈을 구현하여라.

1. Quaternion이라는 이름의 모듈을 생성한다. 이 모듈은 glm::quat을 멤버 변수로 가진다.

2. glm::quat 멤버변수는 { w=1, x, y, z = 0 }으로 초기화한다.

3. 다음의 생성자를 추가하여라.
- Quaternion() = default;
- Quaternion(const Quaternion &src) = default;
- constexpr Quaternion(const glm::quat &src);
- constexpr Quaternion(const float w, const float x, const float y, const float z);
- Quaternion(const glm::vec3 &eulerAngles);
- Quaternion(const float pitch, const float yaw, const float roll);
- Quaternion(const float angle, const glm::vec3 &axis);
- Quaternion(const glm::mat3 &rotationMatrix);
- Quaternion(const glm::mat4 &rotationMatrix);

4. 다음의 함수를 추가하여라.
- constexpr void set(const glm::quat &src);
- constexpr void set(const float w, const float x, const float y, const float z);
- void set(const glm::vec3 &eulerAngles);
- void set(const float pitch, const float yaw, const float roll);
- void set(const float angle, const glm::vec3 &axis);
- void set(const glm::mat3 &rotationMatrix);
- void set(const glm::mat4 &rotationMatrix);
- void orient(const glm::vec3 &forward, const glm::vec3 &referenceUp = { 0.f, 1.f, 0.f });
- void rotateGlobal(const glm::vec3 &eularAngles);
- void rotateGlobal(const float pitch, const float yaw, const float roll);
- void rotateGlobal(const float angle, const glm::vec3 &axis);
- void rotateLocal(const glm::vec3 &eulerAngles);
- void rotateLocal(const float pitch, const float yaw, const float roll);
- void rotateFPS(const float pitch, const float yaw, const glm::vec3 &referenceUp = { 0.f, 1.f, 0.f });
- glm::vec3 getEularAngles() const;
- void getEularAngles(glm::vec3 &retVal) const;
- glm::mat4 getMatrix() const;
- Quaternion inverse() const;
- std::pair<float, glm::vec3> getAngleAxis() const;
- friend Quaternion operator*(const Quaternion &lhs, const Quaternion &rhs);

5. 기존 프로젝트에서 Transform 모듈의 rotation 기능을 Quaternion 기반의 연산으로 대체하고, 프로젝트가 정상 실행되는 것을 확인한다.

**Comment by sein519** [comment]
다음의 명세를 만족하는 DemoScene을 구현하여라.
- 화면 중앙에 무회전 상태의 Box 그래픽을 출력한다.
- 키버튼 '1'을 누르면 global rotate 모드로, '2'키를 누르면 local rotate 모드로, '3'키를 누르면 fps rotate 모드로 전환된다.
- rotate 모드에 따라 아래의 기능이 적절히 작동되도록 한다.
- insert/delete 키를 누르면 box의 pitch 값을 증가 및 감소시킨다.
- home/end 키를 누르면 box의 yaw 값을 증가 및 감소시킨다.
- page up/page down 키를 누르면 box의 roll 값을 증가 및 감소시킨다. 단 FPS 모드에서는 아무 동작도 수행되지 않도록 한다.
- 방향키 up/down 버튼을 누르면 box가 현재 forward를 기준으로 전/후진 하도록 한다.
- 뱡향키 right/left 버튼을 누르면 box가 현재 horizontal을 기준으로 우측/좌측이동 하도록 한다. 단 horizontal은 local basis 기준으로 좌측 방향임에 주의한다.
- **모든 명세를 동작별로 구분하여 GIF 영상을 캡처한 뒤 코멘트로 첨부한다.**

**Comment by jin519** [comment]
![global](https://user-images.githubusercontent.com/47758611/84875099-7c123980-b0c0-11ea-8420-e136fab86eb4.gif)
![local](https://user-images.githubusercontent.com/47758611/84875108-7ddbfd00-b0c0-11ea-8ae9-5150a18b9415.gif)
![fps](https://user-images.githubusercontent.com/47758611/84875117-803e5700-b0c0-11ea-9a13-2b6f52940d23.gif)
![translate](https://user-images.githubusercontent.com/47758611/84875126-82a0b100-b0c0-11ea-806a-8f1555ae4047.gif)

**Comment by sein519** [comment]
![KakaoTalk_20200617_174456846](https://user-images.githubusercontent.com/47758621/84890162-ffd62100-b0d4-11ea-9e1f-5aa1bd453aa2.gif)

**Comment by sein519** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/47758621/84890812-db2e7900-b0d5-11ea-8cca-818245a2fc27.gif)
