### ISSUE TITLE
HW20: Projection matrix 구현

### ISSUE THREAD

**Issue by sein519** [Twin-Monkeys/Poodle#37]
OrthoCamera.cpp 및 PerspectiveCamera.cpp에 다음의 함수를 구현하고, 기존의 ortho와 perspective 함수를 대체하여 정상 작동되는 지 확인하시오.

1. OrthoCamera에 다음의 함수를 구현하시오.
mat4 myOrtho(const float left, const float right, const float bottom, const float top, const float zNear, const float zfar);

2. PerspectiveCamera에 다음의 함수를 구현하시오.
mat4 myFrustum(const float left, const float right, const float bottom, const float top, const float zNear, const float zfar);
mat4 myPerspective(const float fov, const float aspectRatio, const float zNear, const float zFar);
단 myPerspective 함수는 myFrustum()을 이용하여 간접 구현한다.

3. OrthoCamera 및 PerspectiveCamera를 사용하여 Demo가 정상적으로 수행되는 것을 캡처하여 첨부한다.

**Comment by jin519** [comment]
![ortho](https://user-images.githubusercontent.com/47758611/87946209-af3f5280-cadc-11ea-8335-5f4025a029a0.gif)
![perspective](https://user-images.githubusercontent.com/47758611/87946236-b5cdca00-cadc-11ea-82fc-b65b4262eba1.gif)
